### ISSUE TITLE
Request for FBX format support and material importing.

### ISSUE THREAD

**Issue by PeterZhenhh** [Scobalula/ModelMerger#1]
It's a nice tool for merging COD and RE Engine's games character models before importing animations.
Request for FBX format support and material importing so that we can merge some FBX format model exported by other tools like PredatorCZ's MT FRAMEWORK TOOLS for further research on RE5,6,REV,REV2 and other MT FRAMEWORK's games.
Thanks a lot!

**Comment by Scobalula** [comment]
If someone wants to write the code for that, I'll be happy to merge it through a Pull Request, otherwise, it's not something I would ever use, and the features of this tool reflect my use of it.
